PromotionEngine/PromotionEngine/Models/ErrorViewModel.cs
using System;

namespace PromotionEngine.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PromotionEngine/PromotionEngine/Models/ProCharActivePromos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PromotionEngine.Models
{
    public class ProCharActivePromos
    {
        readonly Dictionary<string, int> lstProCharActivePromos = new Dictionary<string, int>();

        /// <summary>
        /// To get all Pro Active Promos
        /// </summary>
        /// <returns>Dictionary<string,int></string></returns>
        public Dictionary<string, int> GetlstProCharActivePromos()
        {
            lstProCharActivePromos.Add("3A", 130);
            lstProCharActivePromos.Add("2B", 45);
            lstProCharActivePromos.Add("C+D", 30);

            return lstProCharActivePromos;
        }
    }
}

PromotionEngine/PromotionEngine/Models/SkuUnitPrice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PromotionEngine.Models
{
    public class SkuUnitPrice
    {
        readonly Dictionary<string, int> lstSkuUnitPrice = new Dictionary<string, int>();

        /// <summary>
        /// Method to get All available SKU and their price
        /// </summary>
        /// <returns>Dictionary<string, int></returns>
        public Dictionary<string, int> GetlstSKUUnitPrice()
        {
            lstSkuUnitPrice.Add("A", 50);
            lstSkuUnitPrice.Add("B", 30);
            lstSkuUnitPrice.Add("C", 20);
            lstSkuUnitPrice.Add("D", 15);

            return lstSkuUnitPrice;
        }
    }
}

PromotionEngine/PromotionEngine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PromotionEngine.Models;

namespace PromotionEngine.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PromotionEngine/PromotionEngine/Controllers/PromotionEngineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PromotionEngine.Models;
using PromotionEngine.Services;

namespace PromotionEngine.Controllers
{
    public class PromotionEngineController : Controller
    {
        private readonly SkuUnitPrice sku = new SkuUnitPrice();
        private readonly ICalculateCartValue _calculateCartValue;

        public PromotionEngineController(ICalculateCartValue calculateCartValue)
        {
            _calculateCartValue = calculateCartValue;
        }
        public IActionResult Index()
        {
            return View();
        }
        //To get all available Sku
        public JsonResult GetSku()
        {
            List<string> skus = sku.GetlstSKUUnitPrice().Keys.ToList();
            return Json(data: skus);
        }

        [HttpPost]
        public async Task<JsonResult> GetTotalCartValue(string[] cartArray)
        {
            //decimal totalSum = 0;
            List<string> cartItem;
            if (cartArray.Length > 0)
            {
                cartItem = cartArray.ToList();
            }
            var (total, finalCart) = await _calculateCartValue.GetTotalAndCartItems(cartArray);
            return new JsonResult(new { total = total, cartitems = finalCart });
        }
    }
}

PromotionEngine/PromotionEngine/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PromotionEngine/PromotionEngine/Views/PromotionEngine/Index.cshtml
@{
    ViewData["Title"] = "Promotion Engine";
}

<div class="container">
    <div class="form-group">
        <h1>Welcome to Promotion Engine</h1>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Add Item</label>
            <div class="col-sm-4">
                <select name="item" id="Sku" class="form-control">
                </select>
            </div>
            <div class="col-sm-6">
                <button type="button" id="btnAddItemToCart" class="btn btn-success">Add To Cart</button>
                <button type="button" id="btnClear" class="btn btn-danger">Clear Cart</button>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2"></label>
            <div class="col-sm-4">
                <button type="button" id="btnGetTotal" class="btn btn-info">Total Cart Value</button>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-4">
                <ul class="list-group" id="cartItemsId"></ul>
            </div>
            <div class="col-sm-2" id="output">
                <h3>Output:</h3>
            </div>
            <div class="col-sm-4" id="cart">
                <label><b>Cart value : </b></label>
                <span id="totalSum"></span>
                <ul id="finalCartlogic">
                </ul>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        $('#output').hide();
        $('#cart').hide();
        //to get All sku in dropdown
        $.ajax({
            dataType: 'json',
            type: 'GET',
            url: 'PromotionEngine/GetSku',
            success: function (data) {
                let option = '';
                for (var i = 0; i < data.length; i++) {
                    option += '<option value="' + data[i] + '">' + data[i] + '</option>';
                }
                $('#Sku').append(option);
            }

        })
    })

    $("#btnClear").click(function () {
        $("#cartItemsId").empty();
        $('#finalCartlogic').empty();
        $("#totalSum").empty();
        $('#output').hide();
        $('#cart').hide();
    });

    //Adding items to cart
    $("#btnAddItemToCart").click(function () {
        var value = $("#Sku").val();
        $("#cartItemsId").append('<li>' + value + '</li>');
    })

    $("#btnGetTotal").click(function () {
        var arr = [];
        //loop to get all added items
        $("#cartItemsId li").each(function () { arr.push($(this).text()) });
        if (arr.length > 0) {
            $.ajax({
                dataType: 'json',
                type: 'POST',
                async: true,
                data: { cartArray: arr },
                url: "PromotionEngine/GetTotalCartValue",
                success: function (data, status) {
                    $('#output').show();
                    $('#cart').show();
                    $("#totalSum").html(data.total);
                    let text = '';
                    for (i = 0; i < data.cartitems.length; i++) {
                        text += '<li>' + data.cartitems[i] + '</li>'
                    }
                    $('#finalCartlogic').append(text);
                },
                error: function (xhr, status, error) { // error callback
                    var err = xhr.responseText;
                    console.log(err);
                }
            });
        } else {
            alert("please add item to cart");
        }
    });
</script>

PromotionEngine/PromotionEngine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PromotionEngine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="PromotionEngine" asp-action="Index">PromotionEngine</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PromotionEngine" asp-action="Index">PromotionEngine</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PromotionEngine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>